### ISSUE TITLE
Do not warn when a parameter is added when unnecessary

### ISSUE THREAD

**Issue by kud** [tricoder42/named-urls#12]
I don't see the point to warn that there's an unknown parameter.

For instance I do that:

```jsx
        url={reverse(
          `${
            current
              ? routes.bill.step.text
              : routes.bill.step.text.amendment
          }`,
          {
            billId,
            stepPosition,
            stepRelation,
            amendmentId: id,
          },
        )}
```

and depending if it's `current` or not, I change the route, but amendment here is needed only if `current` is false, so I've got a warning saying that `:amendmentId` is unknown, which I know and I don't mind, it works. :D

**Comment by kud** [comment]
Oh and even if the warnings are ok, the usecase seems not to work well:

```jsx
        url={reverse(
          `${
            current
              ? routes.bill.step.text
              : routes.bill.step.text.amendment
          }`,
          {
            billId,
            stepPosition,
            stepRelation,
            amendmentId: !current ? id : undefined,
          },
        )}
```

**Comment by kud** [comment]
Giving a warning when an unknown parameter is a point of view. But when this param is undefined, it shouldn't warn at all.

**Comment by kud** [comment]
It forced me to do this:

```
        url={current
          ? reverse(`${routes.bill.step.text}`,
          {
            billId,
            stepPosition,
            stepRelation,
          })
          : reverse(`${routes.bill.step.text.amendment}`,
          {
            billId,
            stepPosition,
            stepRelation,
            amendmentId,
          })
        }
```

which I find it ugly. //

**Comment by kud** [comment]
Well fine, thank you ES6

```
        url={reverse(
          `${
            current
              ? routes.bill.step.text
              : routes.bill.step.text.amendment
          }`,
          {
            billId,
            stepPosition,
            stepRelation,
            ...!current && { amendmentId },
          },
        )}
```

but I'm still interested by your PoV about the warning :D

**Comment by kud** [comment]
Another case with `<Redirect />`. Redirect is able to translate from `from` to `to` the parameters.

For instance you can do:


```
<Redirect from="/:param" to="/:param/index" />
```


I wanted to do the same thing with named-urls this way:

```
<Redirect
            from={`${routes.bill.step}`}
            to={reverse(`${routes.bill.step.text}`, {
              stepRelation: "input",
            })}
          />
```

with

```
import { include } from "named-urls"

const routes = {
  index: "/",
  home: "/home/",
  bill: include("/bill-:billId/", {
    step: include("step-:stepPosition/", {
      text: include(":stepRelation/", {
        amendment: "amendment-:amendmentId/",
      }),
    }),
  }),
  login: "/login/",
  oops: "/oops/",
  sandbox: "/sandbox/:id/",
}

export default routes
```

The thing is it notifies me `Required parameter billId is missing for /bill-:billId/step-:stepPosition/:stepRelation/`

which is quite wrong with `<Redirect>` because `:billId` must stay like that.

A workaround is to do this:

```
          <Redirect
            from={`${routes.bill.step}`}
            to={reverse(`${routes.bill.step.text}`, {
              billId: ":billId",
              stepPosition: ":stepPosition",
              stepRelation: "input",
            })}
          />
```

which is way too explicit here.

**Comment by tricoder42** [comment]
I understand your usecase, but I'm not sure what would be the best approach here. It's useful to know early that you've missed or mispelled a parameter. However, I agree that warning isn't sufficient. It should either fail completely or keep the parameter intact.

What about removing warning for now and we'll figure out how to handle erro cases later? Would you like to send a PR?

**Comment by kud** [comment]
Deal! Thank you :)

**Comment by kud** [comment]
https://github.com/tricoder42/named-urls/pull/14
